create table leads (
    id bigserial primary key,
    business_name varchar(160) not null,
    niche varchar(80) not null,
    city varchar(120) not null,
    state varchar(2) not null,
    address varchar(255),
    phone varchar(30),
    whatsapp varchar(30),
    website varchar(255),
    instagram varchar(255),
    google_maps_url varchar(255),
    google_place_id varchar(160),
    rating numeric(3, 2),
    review_count integer,
    has_website boolean not null default false,
    has_https boolean not null default false,
    responsive boolean not null default false,
    site_slow boolean not null default false,
    opportunity_score integer,
    status varchar(40) not null,
    is_duplicate boolean not null default false,
    lost_reason varchar(40),
    created_at timestamp not null,
    updated_at timestamp not null
);
